name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Format check
      run: cargo fmt --check
      
  build:
    runs-on: ubuntu-latest
    needs: [code_quality]
    steps:
    - uses: actions/checkout@v4
    - name: Install DBUS package
      run: sudo apt install -y libdbus-1-dev
    - name: Build
      run: cargo build --verbose
